// store
export const GET_STORE_LIST = 'GET_STORE_LIST'

// customizeReport
export const GET_CUSTOMIZE_REPORT_LIST_REQUEST = 'GET_CUSTOMIZE_REPORT_LIST_REQUEST'
export const GET_CUSTOMIZE_REPORT_LIST_SUCCESS = 'GET_CUSTOMIZE_REPORT_LIST_SUCCESS'
export const GET_CUSTOMIZE_REPORT_LIST_FAILURE = 'GET_CUSTOMIZE_REPORT_LIST_FAILURE'

export const GET_CUSTOMIZE_REPORT_META = 'GET_CUSTOMIZE_REPORT_META'

export const GET_CUSTOMIZE_REPORT_PREVIEW_REQUEST = 'GET_CUSTOMIZE_REPORT_PREVIEW_REQUEST'
export const GET_CUSTOMIZE_REPORT_PREVIEW_SUCCESS = 'GET_CUSTOMIZE_REPORT_PREVIEW_SUCCESS'
export const GET_CUSTOMIZE_REPORT_PREVIEW_FAILURE = 'GET_CUSTOMIZE_REPORT_PREVIEW_FAILURE'